[package]
name = "kyoku"
version = "0.2.0"
edition = "2024"

[dependencies]
convlog = { git = "https://github.com/Equim-chan/mjai-reviewer.git" }
dotenvy = "0.15.7"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
ureq = "3"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "system-proxy"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "macros"] }
